spring:
  datasource:
    url: jdbc:mysql://localhost/collect?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root_2019
    driver-class-name: com.mysql.cj.jdbc.Driver  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect 